# Form implementation generated from reading ui file '/home/claude/NumericalDigitize/chooseFeatureGUI.ui'
#
# Created by: PyQt5 UI code generator 5.x (converted from PyQt6)
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_chooseFeatureDialog(object):
    def setupUi(self, chooseFeatureDialog):
        chooseFeatureDialog.setObjectName("chooseFeatureDialog")
        chooseFeatureDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        chooseFeatureDialog.resize(470, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(chooseFeatureDialog.sizePolicy().hasHeightForWidth())
        chooseFeatureDialog.setSizePolicy(sizePolicy)
        chooseFeatureDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        chooseFeatureDialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(chooseFeatureDialog)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=chooseFeatureDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.listFeatures = QtWidgets.QListWidget(parent=chooseFeatureDialog)
        self.listFeatures.setObjectName("listFeatures")
        self.gridLayout.addWidget(self.listFeatures, 0, 0, 1, 1)

        self.retranslateUi(chooseFeatureDialog)
        self.buttonBox.accepted.connect(chooseFeatureDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(chooseFeatureDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(chooseFeatureDialog)

    def retranslateUi(self, chooseFeatureDialog):
        _translate = QtCore.QCoreApplication.translate
        chooseFeatureDialog.setWindowTitle(_translate("chooseFeatureDialog", "Choose feature for edit"))
